#! /bin/sh
set -e

filename="/usr/share/initramfs-tools/scripts/local"
oldvalue='mount ${roflag} -o loop -t ${FSTYPE} ${LOOPFLAGS} "/host/${LOOP#/}" ${rootmnt}'
newvalue='loopdev=`losetup -f`; losetup ${loopdev} "/host/${LOOP#/}"; mount ${roflag} -t ${FSTYPE} ${LOOPFLAGS} ${loopdev} ${rootmnt}'

if [ -f $filename ]; then
	if cat $filename | grep "$oldvalue" >/dev/null; then
		sed -i "s%$oldvalue%$newvalue%g" $filename
	fi
fi

exit 0
