#!/bin/sh

#Required programs
python_url="https://www.python.org/ftp/python/2.7.18/python-2.7.18.msi"
python_md5="db6ad9195b3086c6b4cefb9493d738d2"
p7zip_url="https://downloads.sourceforge.net/project/sevenzip/7-Zip/9.20/7z920.msi"
p7zip_md5="9bd44a22bffe0e4e0b71b8b4cf3a80e2"

# Ubuntu packages for mingw32
mingw32_url="http://archive.ubuntu.com/ubuntu/pool/universe/m/mingw32/mingw32_4.2.1.dfsg-2ubuntu1_"
mingw32_binutils_url="http://archive.ubuntu.com/ubuntu/pool/universe/m/mingw32-binutils/mingw32-binutils_2.20-0.2ubuntu1_"
mingw32_runtime_url="http://archive.ubuntu.com/ubuntu/pool/universe/m/mingw32-runtime/mingw32-runtime_3.15.2-0ubuntu1_all.deb"

root="$(cd ${0%/*}/../;pwd)"
export WINEPREFIX="$root"/wine
program_dir="$WINEPREFIX/drive_c/Program"
python_dir="$WINEPREFIX/drive_c/Python27"
python_site="$python_dir/Lib/site-packages"
toolsdir="$root/tools"

download(){
	wget  -P /tmp -O "$2" "$1"
	md5=$(md5sum $2)
	md5=${md5%% *}
	if [ ! "$md5" = "$3" ]; then
		echo "Invalid download for $1, md5 does not match"
		exit 1
	fi
}

install_7z(){
	echo "Installing 7z..."
	download "$p7zip_url" "/tmp/p7zip.msi" "$p7zip_md5"
	wine msiexec /i /tmp/p7zip.msi /quiet
}

install_wine(){
	if [ ! -x /usr/bin/wine -a ! -x /usr/local/bin/wine ]; then
		echo "Installing wine..."
		sudo apt-get install -y wine #TBD do not assume apt
	fi
}

install_mingw32(){
	if [ ! -x /usr/bin/i586-mingw32msvc-gcc -a ! -x /usr/local/bin/i586-mingw32msvc-gcc ]; then
		echo "Installing mingw32..."
		sudo apt-get install -y mingw32 #TBD do not assume apt
	fi
	if [ ! -x /usr/bin/i586-mingw32msvc-gcc -a ! -x /usr/local/bin/i586-mingw32msvc-gcc ]; then
		echo "Installing mingw32 via dpkg..."
		arch=$(dpkg --print-architecture)
		wget "$mingw32_url$arch.deb" -P /tmp -O "/tmp/mingw32.deb"
		wget "$mingw32_binutils_url$arch.deb" -P /tmp -O "/tmp/mingw32-binutils.deb"
		wget "$mingw32_runtime_url" -P /tmp -O "/tmp/mingw32-runtime.deb"
		sudo dpkg -i /tmp/mingw32*.deb
	fi
}

install_unzip(){
	if [ ! -x /usr/bin/unzip -a ! -x /usr/local/bin/unzip ]; then
		echo "Installing unzip..."
		sudo apt-get install -y unzip #TBD do not assume apt
	fi
}

install_python(){
	echo "Installing python..."
	download "$python_url" "/tmp/python.msi" "$python_md5"
    wine msiexec /i /tmp/python.msi /qb /ADDLOCAL=DefaultFeature /ALLUSERS=1
}

install_mock(){
	echo "Installing mock..."
	wine "$python_dir/python.exe" -m pip install mock
}

install_pycrypto(){
	echo "Installing pycrypto..."
    wine "$python_dir/python.exe" -m pip install pycryptodome
}

if [ ! -e "$root/wine" ]; then
	install_wine
fi
if [ ! -x /usr/bin/i586-mingw32msvc-gcc -a ! -x /usr/local/bin/i586-mingw32msvc-gcc ]; then
	install_mingw32
fi
if [ ! -e "$python_dir/python.exe" ]; then
        install_python
fi
if [ ! -e "$python_site/Crypto" ]; then
	install_pycrypto
fi
if [ ! -e "$python_site/Mock" ]; then
	install_mock
fi
if [ ! -e "$program_dir"*"/7-Zip/7z.exe" ]; then
	install_7z
fi