#!/bin/sh

urlgrabber_url="http://linux.duke.edu/projects/urlgrabber/download/urlgrabber-3.1.0.tar.gz"
bittornado_url='http://download2.bittornado.com/download/BitTornado-0.3.17.tar.gz'

root="$(cd ${0%/*}/../;pwd)"

install_urlgrabber(){
    echo "Installing urlgrabber sources..."
	wget -P /tmp "$urlgrabber_url"
	fname="${urlgrabber_url##*/}"
	tar -xzvf "/tmp/$fname" -C "/tmp"
	cp -a /tmp/urlgrabber*/urlgrabber "$root/src/"
}

install_bittornado(){
    echo "Installing bittornado sources..."
	wget -P /tmp "$bittornado_url"
	fname="${bittornado_url##*/}"
	tar -xzvf "/tmp/$fname" -C "/tmp"
	cp -a /tmp/BitTornado*/BitTornado "$root/src/"
}

if [ ! -d "$root/src/urlgrabber" ]; then
	install_urlgrabber
fi

if [ ! -d "$root/src/bittornado" ]; then
	install_bittornado
fi
